version: '2.2'
services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_PASSWORD=
      - POSTGRESQL_USERNAME=
      - POSTGRESQL_DATABASE=
    ports:
      - :5432
    restart: unless-stopped

  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=
    ports:
      - :6379
    restart: unless-stopped
